#!/usr/local/bin/perl -w
#
# $Id$
#
# script to manually add a subnet to our database
#

use strict;
use HOSTDB;

my $debug = 0;
if (defined ($ARGV[0]) and $ARGV[0] eq "-d") {
	shift (@ARGV);
	$debug = 1;
}

if ($#ARGV != 3) {
	die (<<EOT);
Syntax: $0 subnet owner short-desc long-desc
	subnet is the subnet in slash notation (eg. 192.168.1.0/24)
	owner is the HOSTDB::Auth identifier that will be able to modify things in this subnet
	short-desc is what is shown in the overview netplan
	long-desc is the long description of the subnet

EOT
}

my $hostdb = HOSTDB::DB->new (inifile => HOSTDB::get_inifile (),
			      debug => $debug
			     );

my $subnet = $hostdb->create_subnet (4, $ARGV[0]);

die ("Could not create subnet object: " . $hostdb->{error} . "\n") if (! $subnet);

$subnet->owner ($ARGV[1]);
$subnet->short_description ($ARGV[2]);
$subnet->description ($ARGV[3]);

$subnet->commit() or die ("Could not commit subnet object: " . $subnet->{error} . "\n");

exit (0);
