#!/usr/local/bin/perl
#
# $Id$
#
# script to manually add a subnet to our database
#

use strict;
use Config::IniFiles;
#use lib 'blib/lib';
use HOSTDB;

my $debug = 0;
if ($ARGV[0] eq "-d") {
	shift (@ARGV);
	$debug = 1;
}

if ($#ARGV != 2) {
	die (<<EOT);
Syntax: $0 subnet short-desc long-desc
	subnet is the subnet in slash notation (eg. 192.168.1.0/24)
	short-desc is what is shown in the overview netplan
	long-desc is the long description of the subnet

EOT
}

my $hostdbini = Config::IniFiles->new (-file => HOSTDB::get_inifile ());
die ("$0: Config file access problem.\n") unless ($hostdbini);

my $hostdb = HOSTDB::DB->new (dsn => $hostdbini->val ('db', 'dsn'),
			  db => $hostdbini->val ('db', 'database'),
			  user => $hostdbini->val ('db', 'user'),
			  password => $hostdbini->val ('db', 'password'),
			  debug => $debug
			 );

my $subnet = $hostdb->create_subnet (4, $ARGV[0]);

die ("Could not create subnet object: " . $hostdb->{error} . "\n") if (! $subnet);

$subnet->short_description ($ARGV[1]);
$subnet->description ($ARGV[2]);

$subnet->commit() or die ("Could not commit subnet object: " . $subnet->{error} . "\n");

exit (0);
