#!/usr/local/bin/perl -w
#
# $Id$
#
# script to manually add a subnet to our database
#

use strict;
use HOSTDB;
use Getopt::Long;
use vars qw ($opt_debug $opt_force $opt_quiet);

my %o = ();
my $res = GetOptions (
	    "debug",
	    "force",
	    "quiet"
	   );


my $debug = defined ($opt_debug);

my $subnet_name = shift;

if (! $subnet_name) {
	die(<<EOT);
Syntax: [options] $0 subnet
	options:
		--force	really delete the subnet

EOT
}

my $hostdb = HOSTDB::DB->new (inifile => HOSTDB::get_inifile (),
			      debug => $debug
			     );

my $subnet = $hostdb->findsubnet ($subnet_name);

die ("Could not find subnet '$subnet_name' in database\n") if (! $subnet);

if (! defined ($opt_force)) {
	die ("Not removing subnet $subnet_name, you have to delete with force.\n");
}

if (! $subnet->delete ($opt_force?"YES":"WELL, UHH")) {
	die ("Could not delete subnet '$subnet_name': $subnet->{error}\n");
}

exit (0);
