#!/usr/local/bin/perl -w
#
# $Id$
#
# script to manually add a subnet to our database
#

use strict;
use HOSTDB;

my $debug = 0;
if ($ARGV[0] eq "-d") {
	shift (@ARGV);
	$debug = 1;
}


my $subnet_name = shift;
my $check = shift;

if (! $subnet_name) {
	die("Syntax: $0 subnet YES\n");
}

if ($check ne "YES") {
	die ("Not removing subnet $subnet_name since you seem unsure.\n\nSyntax: $0 subnet YES\n");
}

my $hostdb = HOSTDB::DB->new (inifile => HOSTDB::get_inifile (),
			      debug => $debug
			     );

my $subnet = $hostdb->findsubnet ($subnet_name);

die ("Could not find subnet '$subnet_name' in database\n") if (! $subnet);

if (! $subnet->delete ($check)) {
	die ("Could not delete subnet '$subnet_name': $subnet->{error}\n");
}

exit (0);
