#!/usr/bin/perl
#
# $Id$
#
# script to read strictly formatted BIND9 zone files and put all A records
# in our host database.
#

use strict;
use Config::IniFiles;
#use lib 'blib/lib';
use HOSTDB;

my $hostdbini = Config::IniFiles->new (-file => '/usr/local/etc/hostdb.ini');

my $hostdb = HOSTDB::DB->new (dsn => $hostdbini->val ('db', 'dsn'),
			  db => $hostdbini->val ('db', 'database'),
			  user => $hostdbini->val ('db', 'user'),
			  password => $hostdbini->val ('db', 'password'),
			  debug => $debug
			 );

my @files = @ARGV;
my $default_ttl;

if ($#files == -1) {
	die ("Syntax: $0 zonefiles\n");
}

foreach my $file (@files) {
	open (FIL, "< $file") or die ("Could not open $file for reading: $!\n");

	my $imported = 0;
	$default_ttl = 0;
	my @delayed;
	while (my $rad = <FIL>) {
		chomp ($rad);
		
		$default_ttl = $1 if ($rad =~ /^\$TTL\s+(\d+)/);

		if ($rad =~ /^(b2-gw2|ny-gw2|physto-gw|stud-gw|su2-gw)\./) {
			warn ("skipping known broken DNS record for '$1'\n");
			next;
		}
		
		if ($rad =~ /^(.+?)\s+(\d+)\s+A\s+([\d\.]+)$/) {
			my ($name, $ttl, $ip) = ($1, $2, $3);
			
			if ($name =~ /^(mbox|mx)\.su\.se\.$/) {
				my @info = ($name, $ttl, $ip);
				push (@delayed, \@info);
				next;
			}
			
			$imported++ if (add_host ($name, $ttl, $ip));
		}
	}

	foreach my $arrayref (@delayed) {
		my ($name, $ttl, $ip) = @{ $arrayref };

		$imported++ if (add_host ($name, $ttl, $ip));
	}

	print ("Imported $imported A RR's from file $file\n");
	
	close (FIL);
}

print ("done\n");

sub add_host
{
	my ($name, $ttl, $ip) = @_;
	
	my $host = $hostdb->create_host();

	if ($name =~ /^(mbox|mx)\.su\.se\.$/) {
		my $super_host = $hostdb->findhostbyip ($ip);
		$host->set_partof ($super_host->{id}) if ($super_host->{id});
	}
			
	my $valid = 1;
	$host->set_hostname ("$name") or warn ($host->{error}), $valid = 0;
	$host->set_ip ("$ip") or warn ($host->{error}), $valid = 0;
	$host->set_ttl ("$ttl") if ($ttl != $default_ttl);
	$host->set_user ("import") or warn ($host->{error}), $valid = 0;
	$host->set_reverse ("Y") or warn ($host->{error}), $valid = 0;
			
	$host->commit() if ($valid);

	return $valid;
}

