#!/usr/local/bin/perl
#
# $Id$
#
# script to read host entrys from database
#

use strict;
use Config::IniFiles;
#use lib 'blib/lib';
use HOSTDB;

my $debug = 0;
if ($ARGV[0] eq "-d") {
	shift (@ARGV);
	$debug = 1;
}

my $hostdbini = Config::IniFiles->new (-file => HOSTDB::get_inifile ());

my $hostdb = HOSTDB::DB->new (dsn => $hostdbini->val ('db', 'dsn'),
			  db => $hostdbini->val ('db', 'database'),
			  user => $hostdbini->val ('db', 'user'),
			  password => $hostdbini->val ('db', 'password'),
			  debug => $debug
			 );

my @searchfor = @ARGV;

if ($#searchfor == -1) {
	die ("Syntax: $0 [-d] hostname ...\n");
}

my $first = 1;
my $match_count = 0;

foreach my $t_search (sort @searchfor) {
	if (! $hostdb->is_valid_fqdn ($t_search)) {
		warn ("Invalid FQDN '$t_search'\n");
		next;
	}

	my @hostlist = $hostdb->findhostbyname ($t_search);
	if ($#hostlist == -1) {
		warn ("No entrys matching '$t_search'\n");
		next;
	}
	
	foreach my $matching_host_ref (@hostlist) {
		foreach my $host (@$matching_host_ref) {
			printf ("%-7s %-7s %-16s %s\n", "id", "partof", "ip", "hostname"),
				$first = 0 if ($first);

			printf ("%-7s %-7s %-16s %s\n", $host->id (),
				$host->partof () == 0?"-":$host->partof (),
				$host->ip (), $host->hostname ());

			$match_count++;
		}
		print ("\n");
	}
}

exit ($match_count == 0);
