#!/usr/local/bin/perl -w
#
# $Id$
#
# script to read host entrys from database
#

use strict;
use Config::IniFiles;
#use lib 'blib/lib';
use HOSTDB;

my $debug = 0;
if ($ARGV[0] eq "-d") {
	shift (@ARGV);
	$debug = 1;
}

my $hostdbini = Config::IniFiles->new (-file => HOSTDB::get_inifile ());
die ("$0: Config file access problem.\n") unless ($hostdbini);

my $hostdb = HOSTDB::DB->new (dsn => $hostdbini->val ('db', 'dsn'),
			  db => $hostdbini->val ('db', 'database'),
			  user => $hostdbini->val ('db', 'user'),
			  password => $hostdbini->val ('db', 'password'),
			  debug => $debug
			 );

my @searchfor = @ARGV;

if ($#searchfor == -1) {
	die ("Syntax: $0 [-d] hostname ...\n");
}

my $first = 1;
my $match_count = 0;

foreach my $t_search (sort @searchfor) {
	my @hostlist = $hostdb->findhostbyname ($t_search);
	if ($#hostlist == -1) {
		warn ("No entrys matching '$t_search'\n");
		next;
	}
	
	foreach my $host (@hostlist) {
		printf "%-7s %-7s %-16s %s\n", "id", "partof", "ip", "hostname",
			$first = 0 if ($first);

		printf "%-7s %-7s %-16s %s\n", $host->id (),
			defined ($host->partof ())?$host->partof ():"-",
			$host->ip (), $host->hostname ();

		$match_count++;
	}
}

exit ($match_count == 0);
