#!/usr/local/bin/perl -w
#
# $Id$
#
# script to read host entrys from database

use strict;
use Config::IniFiles;
#use lib 'blib/lib';
use HOSTDB;
use Getopt::Std;
use vars qw ($opt_h $opt_d);

getopts ('hd');

my $debug = defined ($opt_d);

if ($opt_h) {
	die ("Syntax: $0 [-d] ip ...\n");
}

my $hostdbini = Config::IniFiles->new (-file => HOSTDB::get_inifile ());

my $hostdb = HOSTDB::DB->new (dsn => $hostdbini->val ('db', 'dsn'),
			  db => $hostdbini->val ('db', 'database'),
			  user => $hostdbini->val ('db', 'user'),
			  password => $hostdbini->val ('db', 'password'),
			  debug => $debug
			 );

my @searchfor = @ARGV;

if ($#searchfor == -1) {
	die ("Syntax: $0 [-d] IP-address ...\n");
}

my $first = 1;
my $match_count = 0;

foreach my $t_search (sort @searchfor) {
	if (! $hostdb->is_valid_ip ($t_search)) {
		warn ("Invalid IP address '$t_search'\n");
		next;
	}

	my @hostlist = $hostdb->findhostbyip ($t_search);
	if ($#hostlist == -1) {
		warn ("No entrys matching '$t_search'\n");
		next;
	}

	foreach my $host (@hostlist) {
		printf "%-7s %-7s %-16s %s\n", "id", "partof", "ip", "hostname",
			$first = 0 if ($first);

		printf "%-7s %-7s %-16s %s\n", $host->id (),
			defined ($host->partof ())?$host->partof ():"-",
			$host->ip (), $host->hostname ();

		$match_count++;
	}

	print ("\n");
}

exit ($match_count == 0);
